services:
  galpaocrm-db:
    image: mariadb:latest
    container_name: galpaocrm-db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-file-per-table=1
    environment:
      TZ: ${TZ}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - galpaocrm-db:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - galpaocrm-net

  galpaocrm:
    image: danielmonteirodc/galpaocrm:9.3.8
    container_name: galpaocrm
    environment:
      TZ: ${TZ}
      ESPOCRM_DATABASE_PLATFORM: Mysql
      ESPOCRM_DATABASE_HOST: galpaocrm-db
      ESPOCRM_DATABASE_PORT: 3306
      ESPOCRM_DATABASE_NAME: ${MARIADB_DATABASE}
      ESPOCRM_DATABASE_USER: ${MARIADB_USER}
      ESPOCRM_DATABASE_PASSWORD: ${MARIADB_PASSWORD}

      ESPOCRM_ADMIN_USERNAME: ${ESPOCRM_ADMIN_USERNAME}
      ESPOCRM_ADMIN_PASSWORD: ${ESPOCRM_ADMIN_PASSWORD}

      ESPOCRM_SITE_URL: ${ESPOCRM_SITE_URL}

      ESPOCRM_LANGUAGE: pt_BR
      ESPOCRM_DATE_FORMAT: DD/MM/YYYY
      ESPOCRM_TIME_FORMAT: HH:mm
      ESPOCRM_TIME_ZONE: ${TZ}
      ESPOCRM_WEEK_START: 1
      ESPOCRM_DEFAULT_CURRENCY: BRL
      ESPOCRM_THOUSAND_SEPARATOR: .
      ESPOCRM_DECIMAL_MARK: ","

      ESPOCRM_CONFIG_THEME: Galpao
      ESPOCRM_CONFIG_APPLICATION_NAME: "Galpão Design CRM"

      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_URL: "${WEBSOCKET_URL}"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://galpaocrm-websocket:7777"
    volumes:
      - galpaocrm-data:/var/www/html
    restart: unless-stopped
    depends_on:
      galpaocrm-db:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - galpaocrm-net

  galpaocrm-daemon:
    image: danielmonteirodc/galpaocrm:9.3.8
    container_name: galpaocrm-daemon
    environment:
      TZ: ${TZ}
    volumes:
      - galpaocrm-data:/var/www/html
    restart: unless-stopped
    entrypoint: docker-daemon.sh
    depends_on:
      galpaocrm-db:
        condition: service_healthy
      galpaocrm:
        condition: service_started
    networks:
      - galpaocrm-net

  galpaocrm-websocket:
    image: danielmonteirodc/galpaocrm:9.3.8
    container_name: galpaocrm-websocket
    environment:
      TZ: ${TZ}
      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_URL: "${WEBSOCKET_URL}"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://galpaocrm-websocket:7777"
    volumes:
      - galpaocrm-data:/var/www/html
    restart: unless-stopped
    entrypoint: docker-websocket.sh
    depends_on:
      galpaocrm-db:
        condition: service_healthy
      galpaocrm:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - galpaocrm-net

volumes:
  galpaocrm-db:
  galpaocrm-data:

networks:
  galpaocrm-net:
    driver: bridge
